PACKAGE_NAME="rockpi-rpi-touchscreen"
PACKAGE_VERSION="0.2.1"
BUILT_MODULE_NAME[0]="raspits_ft5426"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates/dkms"
BUILT_MODULE_NAME[1]="panel_rockpi_rpi_touchscreen"
BUILT_MODULE_LOCATION[1]="."
DEST_MODULE_LOCATION[1]="/updates/dkms"
MAKE[0]="'sh' scripts/dkms-make.sh ${kernelver} make KDIR=/lib/modules/${kernelver}/build modules"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"
AUTOINSTALL="yes"
