PACKAGE_NAME="rockpi-rpi-touchscreen"
PACKAGE_VERSION="0.1.1"
BUILT_MODULE_NAME[0]="raspits_ft5426"
DEST_MODULE_LOCATION[0]="/updates/dkms"
MAKE[0]="'sh' scripts/dkms-make.sh ${kernelver} make KDIR=/lib/modules/${kernelver}/build modules"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"
AUTOINSTALL="yes"
